GET http://localhost:3000/api/TodoService
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InNraWxscyI6WyJSZWFjdCIsIk5vZGVqcyIsIkphdmFTY3JpcHQiXSwiX2lkIjoiNWU1MzYyMTFmYTg0ZTIwZTQwZGRiODk2IiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJwYXNzd29yZCI6IiQyYiQxMCRNUGZqZHRyNnE4UXZmOHNvQXhoLm11ZjZPaE9GLmlheUpkdWppLjFEZzc2ZDRyZUtGcHd2TyIsImFkZHJlc3MiOnsiY2l0eSI6IkJlbmdhbHVydSIsImNvdW50cnkiOiJJbmRpYSJ9LCJjcmVhdGVkT24iOiIyMDIwLTAyLTI0VDA1OjQxOjM3Ljc3NFoiLCJfX3YiOjB9LCJpYXQiOjE1ODI2OTQwNjksImV4cCI6MTU4MjY5NzY2OX0.0ZPr1BlWq-Ti5a8GlVmPuMEgUBkxhChw_B81R6kygg0

###
GET http://localhost:3000/api/TodoService/5e54b70c9c5b5a0ea83bd123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InNraWxscyI6WyJSZWFjdCIsIk5vZGVqcyIsIkphdmFTY3JpcHQiXSwiX2lkIjoiNWU1MzYyMTFmYTg0ZTIwZTQwZGRiODk2IiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJwYXNzd29yZCI6IiQyYiQxMCRNUGZqZHRyNnE4UXZmOHNvQXhoLm11ZjZPaE9GLmlheUpkdWppLjFEZzc2ZDRyZUtGcHd2TyIsImFkZHJlc3MiOnsiY2l0eSI6IkJlbmdhbHVydSIsImNvdW50cnkiOiJJbmRpYSJ9LCJjcmVhdGVkT24iOiIyMDIwLTAyLTI0VDA1OjQxOjM3Ljc3NFoiLCJfX3YiOjB9LCJpYXQiOjE1ODI2OTQwNjksImV4cCI6MTU4MjY5NzY2OX0.0ZPr1BlWq-Ti5a8GlVmPuMEgUBkxhChw_B81R6kygg0

### create new todo
POST http://localhost:3000/api/TodoService
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InNraWxscyI6WyJSZWFjdCIsIk5vZGVqcyIsIkphdmFTY3JpcHQiXSwiX2lkIjoiNWU1MzYyMTFmYTg0ZTIwZTQwZGRiODk2IiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJwYXNzd29yZCI6IiQyYiQxMCRNUGZqZHRyNnE4UXZmOHNvQXhoLm11ZjZPaE9GLmlheUpkdWppLjFEZzc2ZDRyZUtGcHd2TyIsImFkZHJlc3MiOnsiY2l0eSI6IkJlbmdhbHVydSIsImNvdW50cnkiOiJJbmRpYSJ9LCJjcmVhdGVkT24iOiIyMDIwLTAyLTI0VDA1OjQxOjM3Ljc3NFoiLCJfX3YiOjB9LCJpYXQiOjE1ODI2OTQwNjksImV4cCI6MTU4MjY5NzY2OX0.0ZPr1BlWq-Ti5a8GlVmPuMEgUBkxhChw_B81R6kygg0

{
    "title": "buy coffee",
    "createdBy": "testuser1"
}

###
PUT http://localhost:3000/api/TodoService/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InNraWxscyI6WyJSZWFjdCIsIk5vZGVqcyIsIkphdmFTY3JpcHQiXSwiX2lkIjoiNWU1MzYyMTFmYTg0ZTIwZTQwZGRiODk2IiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJwYXNzd29yZCI6IiQyYiQxMCRNUGZqZHRyNnE4UXZmOHNvQXhoLm11ZjZPaE9GLmlheUpkdWppLjFEZzc2ZDRyZUtGcHd2TyIsImFkZHJlc3MiOnsiY2l0eSI6IkJlbmdhbHVydSIsImNvdW50cnkiOiJJbmRpYSJ9LCJjcmVhdGVkT24iOiIyMDIwLTAyLTI0VDA1OjQxOjM3Ljc3NFoiLCJfX3YiOjB9LCJpYXQiOjE1ODI2OTQwNjksImV4cCI6MTU4MjY5NzY2OX0.0ZPr1BlWq-Ti5a8GlVmPuMEgUBkxhChw_B81R6kygg0

{
    "todo": {
        "_id": "5e54b70c9c5b5a0ea83bd123",
        "title": "Add update functionality - 7th time",
        "completed": false
    }
}

###
DELETE http://localhost:3000/api/TodoService/5e54b48a30a1870dde8124e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InNraWxscyI6WyJSZWFjdCIsIk5vZGVqcyIsIkphdmFTY3JpcHQiXSwiX2lkIjoiNWU1MzYyMTFmYTg0ZTIwZTQwZGRiODk2IiwidXNlcm5hbWUiOiJ0ZXN0dXNlcjEiLCJwYXNzd29yZCI6IiQyYiQxMCRNUGZqZHRyNnE4UXZmOHNvQXhoLm11ZjZPaE9GLmlheUpkdWppLjFEZzc2ZDRyZUtGcHd2TyIsImFkZHJlc3MiOnsiY2l0eSI6IkJlbmdhbHVydSIsImNvdW50cnkiOiJJbmRpYSJ9LCJjcmVhdGVkT24iOiIyMDIwLTAyLTI0VDA1OjQxOjM3Ljc3NFoiLCJfX3YiOjB9LCJpYXQiOjE1ODI2OTQwNjksImV4cCI6MTU4MjY5NzY2OX0.0ZPr1BlWq-Ti5a8GlVmPuMEgUBkxhChw_B81R6kygg0